#!/usr/bin/env bash

# configuration file for my vim session
lint() {
    cd $VIM_PROJPATH && 
    black $VIM_PROJNAME && 
    pylint $VIM_PROJNAME && 
    mypy --show-error-codes --disable-error-code attr-defined $VIM_PROJNAME
}

generate_makefile() {
    echo "\
PROJECT = $VIM_PROJNAME

all:
	make format && make lint && make typecheck && make badge

format:
	black \$(PROJECT)

typecheck:
	mypy --show-error-codes --disable-error-code attr-defined \$(PROJECT)

badge:
	python3 utils/create_badge.py -c "make lint"

lint:
	pylint -d fixme --exit-zero \$(PROJECT)" > $VIM_PROJPATH/Makefile
}
    
export -f lint
export VIM_PROJNAME="pytermgui"
export VIM_PROJCONF="$BASH_SOURCE"
export VIM_PROJPATH="$(realpath `dirname $VIM_PROJCONF`)"
export VIM_COMMAND="python3 $VIM_PROJPATH/tests/ongoing.py"
export VIM_NOTES="$VIM_PROJPATH/notes.md"

generate_makefile
echo "Set up project \"$VIM_PROJNAME\" at path \"$VIM_PROJPATH\"."
