#!/usr/bin/env bash

# configuration file for my vim session
lint() {
    cd $VIM_PROJPATH && 
    black $VIM_PROJNAME && 
    pylint $VIM_PROJNAME && 
    mypy --show-error-codes --disable-error-code attr-defined $VIM_PROJNAME
}

export -f lint
export VIM_PROJNAME="pytermgui"
export VIM_PROJCONF="$BASH_SOURCE"
export VIM_PROJPATH="$(realpath `dirname $VIM_PROJCONF`)"
export VIM_COMMAND="python3 $VIM_PROJPATH/tests/container_test.py"
export VIM_NOTES="$VIM_PROJPATH/notes.md"

echo "Set up project \"$VIM_PROJNAME\" at path \"$VIM_PROJPATH\"."
